### ISSUE TITLE
Nested stages

### ISSUE THREAD

**Issue by heug** [circleci/jenkinsfile-converter#24]
**Describe the bug**
JFC does not support Jenkinsfiles with nested stages. e.g. stages -> stage -> parallel -> stage -> stages

**To Reproduce**
`node index.js ./test/configs/declarative-examples/simple-examples/sequentialStages.groovy`

**Expected behavior**
At least a helpful error message to be surfaces, at best a valid config!

**Actual behavior**
```
Error: Error in mapping. Details:
  TypeError: Cannot read property '0' of undefined
      at mapJob (/Users/eugenechoe/sandbox/cci/jfc/mapping/mapper.js:50:39)
      at /Users/eugenechoe/sandbox/cci/jfc/mapping/mapper.js:78:9
      at Array.forEach (<anonymous>)
      at /Users/eugenechoe/sandbox/cci/jfc/mapping/mapper.js:77:22
      at Array.forEach (<anonymous>)
      at mapStages (/Users/eugenechoe/sandbox/cci/jfc/mapping/mapper.js:59:10)
      at map (/Users/eugenechoe/sandbox/cci/jfc/mapping/mapper.js:28:5)
      at Object.jenkinsToCCI (/Users/eugenechoe/sandbox/cci/jfc/main.js:37:26)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
      at async /Users/eugenechoe/sandbox/cci/jfc/index.js:4:15
    at Object.jenkinsToCCI (/Users/eugenechoe/sandbox/cci/jfc/main.js:43:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async /Users/eugenechoe/sandbox/cci/jfc/index.js:4:15
```

**Screenshots**

**Additional context**
Places to start investigation:
https://github.com/circleci/jenkinsfile-converter/blob/dev/mapping/mapper.js#L74
https://github.com/circleci/jenkinsfile-converter/blob/dev/mapping/mapper.js#L50

**Comment by Jaryt** [comment]
Completed on https://github.com/circleci/jenkinsfile-converter/tree/nested-stages

**Comment by makotom** [comment]
Marking this as done for now; if further works is indeed required, let's create a new ticket as it will be a new additional work.
